on: push
name: Repo Checks
jobs:
  check_allowed_files:
    runs-on: self-hosted
    container:
      image: ghcr.io/sta663-sp23/sta663-base:latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(
            c("hw1.ipynb", "advent.py", "wordle.py", "README.*", "data/*")
          )
        })
      shell: Rscript {0}
  check_renders:
    needs: check_allowed_files
    runs-on: self-hosted
    container:
      image: ghcr.io/sta663-sp23/sta663-base:latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Check Renders
      run: |
        quarto render hw1.ipynb --execute --to html --embed-resources
    
    - name: Archive html
      uses: actions/upload-artifact@master
      with:
        name: html
        path: hw1.html